name: Playwright Tests
on:
  push:
    branches: [main, next]
  pull_request:
    branches: [main, next]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: yarn
      - name: Install Playwright
        run: yarn packages/playwright-msw playwright install --with-deps
      - name: Build playwright-msw
        run: yarn packages/playwright-msw run build
      - name: Test playwright-msw
        run: yarn packages/playwright-msw run test
      - name: Build the example app
        run: yarn packages/example run build
      - name: Run the example app's tests
        run: yarn packages/example run test
      - name: Run the example-vue app's tests
        run: yarn packages/example-vue run test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: packages/example/tests/playwright/report
          retention-days: 30
