name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: yarn
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Build playwright-msw
        run: yarn packages/playwright-msw run build
      - name: Build the example app
        run: yarn packages/example run build
      - name: Run the example app's Playwright tests
        run: yarn packages/example run test:playwright
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: packages/example/tests/playwright/report
          retention-days: 30
